### ISSUE TITLE
Linked class is broken

### ISSUE THREAD

**Issue by ExposedCat** [vinceliuice/Orchis-theme#122]
Linked text entry and button looks weird due to rounded corners.
**Adwaita dark**:
![image](https://user-images.githubusercontent.com/44642024/125916814-899988e5-e4bc-402d-919f-f3095c0355c1.png)
**Orchis dark** (built from github):
![image](https://user-images.githubusercontent.com/44642024/125916954-7b5726dd-7297-42de-8cdc-6141b0c73583.png)

**Comment by vinceliuice** [comment]
What's this app?

**Comment by ExposedCat** [comment]
@vinceliuice thx for fast reply. Orchis is the best GTK theme ever 👍.
The app is **Text Pieces**.
Flathub: https://flathub.org/apps/details/com.github.liferooter.textpieces
GitHub: https://github.com/liferooter/textpieces.

**Comment by vinceliuice** [comment]
Thank you, I'll fix this

**Comment by ExposedCat** [comment]
@vinceliuice I think it could be fixed with this styles:
```css
.linked *:nth-child(odd) {
	border-top-right-radius: 0;
	border-bottom-right-radius: 0;
	margin-right: 0;
}
.linked *:nth-child(even) {
	border-top-left-radius: 0;
	border-bottom-left-radius: 0;
	margin-left: 0;
}
```
